### ISSUE TITLE
Unexpected Terraform Plan Changes to Canned Response Libraries in Routing Queues

### ISSUE THREAD

**Issue by JiteshSonkusare** [MyPureCloud/terraform-provider-genesyscloud#1618]
Terraform detects unexpected changes in canned_response_libraries.library_ids when reapplying a Genesys Cloud Routing Queue, even when no actual modifications are made. This leads to unnecessary updates and deployment inconsistencies.

1. Initial terraform plan / apply (Successful Deployment)
+ canned_response_libraries {
    + library_ids = [
        + "51d22d29-dd6d-4a8c-8c04-627f9e3c8750",
        + "52e49e0f-ea68-4aee-9363-6209d6191855",
        + "694afa2e-709f-433b-b43a-40e0c199ab06",
        + "fd276c7f-274a-4c70-887f-c61cdab66e07",
      ]
    + mode = "SelectedOnly"
}

2. Subsequent terraform plan (No Changes to Canned Response Libraries, but still diff detected)
~ canned_response_libraries {
    ~ library_ids = [
        - "52e49e0f-ea68-4aee-9363-6209d6191855",
        - "fd276c7f-274a-4c70-887f-c61cdab66e07",
          "51d22d29-dd6d-4a8c-8c04-627f9e3c8750",
        + "52e49e0f-ea68-4aee-9363-6209d6191855",
          "694afa2e-709f-433b-b43a-40e0c199ab06",
        + "fd276c7f-274a-4c70-887f-c61cdab66e07",
      ]
}

- Expected Behavior
  Terraform should only detect actual additions/removals, not reordering.

- Impact
   Causes unnecessary Terraform updates on every apply.
   Creates deployment inconsistencies despite no real changes in Genesys Cloud.

While looking into the code I found that,
https://github.com/MyPureCloud/terraform-provider-genesyscloud/blob/main/genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go

"library_ids": {
    Description: "Set of canned response library IDs associated with the queue. Populate this field only when the mode is set to SelectedOnly.",
    Optional: true,
    Type: schema.TypeList,
    Elem: &schema.Schema{Type: schema.TypeString},
}

**Type: schema.TypeList**
The issue here is that TypeList enforces an ordered list, meaning Terraform detects changes even when the order of IDs is different but the contents remain the same. This is causing unnecessary updates when no real changes have been made.
It might help by changing TypeList to TypeSet, as TypeSet treats values as an unordered collection.

**Comment by charliecon** [comment]
Hi @JiteshSonkusare 

Thanks for raising the issue and for all the information. We just merged a pull request to fix this issue. You will see these changes on v1.61.0 , which we plan to release sometime this week. 

-Charlie

**Comment by JiteshSonkusare** [comment]
@charliecon Can you please confirm the changes or fix has been added to release v1.61.0.

**Comment by charliecon** [comment]
Hi @JiteshSonkusare 

Yes, they are included in v1.61.0

**Comment by JiteshSonkusare** [comment]
Hi @charliecon, The issue still persists, and the code appears unchanged. This concerns the routing-queue resource - specifically, when attempting to generate a plan for routing queues.

Please refer to the previously shared URL:
https://github.com/MyPureCloud/terraform-provider-genesyscloud/blob/main/genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go

Could you please confirm whether this has been fixed? I’m unable to see any updates or changes in the code.

**Comment by charliecon** [comment]
Hi @JiteshSonkusare 

That was my mistake. It looks like I did a simple project search for "library_ids" and made the changes to another resource that has a field with the same name. Silly mistake on my part. Fixing the routing queue resource now..

**Comment by JiteshSonkusare** [comment]
Hi @charliecon
Ah, easy mistake to make! No worries - looking forward to the fix.

**Comment by charliecon** [comment]
Hi @JiteshSonkusare 

v1.62.0 has been released. This should provide the fix for you. 

Thanks again for raising the issue!

-Charlie

**Comment by JiteshSonkusare** [comment]
Yes! v1.62.0 has fix this issue! Thanks :)
